#!/usr/bin/env bash
# =============================================================================
# infra/agents.sh — AI Agent Key File
# =============================================================================
# Extracts agent-relevant API keys from /etc/dev-server/env and writes them
# to /etc/dev-server/agent-env (world-readable).
#
# The agent CLI tools themselves (copilot, claude, codex, opencode) are
# pre-installed inside the workspace Docker image (coder/Dockerfile).
# This file is bind-mounted read-only into each workspace container so the
# CLIs can pick up their authentication tokens at runtime.
#
# Infrastructure secrets (CLOUDFLARE_API_TOKEN, CLOUDFLARE_ZONE_ID, etc.)
# are deliberately NOT included.
# =============================================================================
set -euo pipefail

LOG_FILE="${LOG_FILE:-/var/log/dev-server-provision.log}"
log() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] [agents] $*" | tee -a "$LOG_FILE"; }

ENV_FILE="${ENV_FILE:-/etc/dev-server/env}"
AGENT_ENV_FILE="/etc/dev-server/agent-env"

if [[ ! -f "$ENV_FILE" ]]; then
  log "WARN: $ENV_FILE not found — skipping agent-env creation."
  exit 0
fi

# ---------------------------------------------------------------------------
# Extract agent-relevant keys only
# ---------------------------------------------------------------------------
log "Writing agent API key file → $AGENT_ENV_FILE …"

{
  echo "# Agent API keys — auto-generated by agents.sh"
  echo "# Bind-mounted read-only into Coder workspace containers."
  echo "# Do NOT add infrastructure secrets (Cloudflare, etc.) here."
  echo ""
  for key in GITHUB_TOKEN OPENAI_API_KEY ANTHROPIC_API_KEY GOOGLE_API_KEY \
             CODEX_OPENAI_AUTH_CODE OPENCODE_PROVIDER \
             ENABLE_AGENT_COPILOT ENABLE_AGENT_CLAUDE ENABLE_AGENT_GEMINI \
             ENABLE_AGENT_CODEX ENABLE_AGENT_OPENCODE \
             STARTER_TEMPLATE; do
    value="$(grep "^${key}=" "$ENV_FILE" | cut -d= -f2- || true)"
    echo "${key}=${value}"
  done
} > "$AGENT_ENV_FILE"

chmod 0644 "$AGENT_ENV_FILE"
log "Agent key file written ($(wc -l < "$AGENT_ENV_FILE") lines)."
log "Note: AI agent CLIs are installed inside the workspace Docker image."

