"""Tests for the importer module."""

from __future__ import annotations

import os
import tempfile
import textwrap
import unittest
from pathlib import Path

from configurator.importer import (
    find_config_files,
    load_config_file,
    parse_cloud_init,
    parse_rvs_config,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

_CLOUD_INIT_SAMPLE = textwrap.dedent("""\
    #cloud-config
    write_files:
      - path: /etc/dev-server/env
        permissions: "0600"
        owner: root:root
        content: |
          DOMAIN=example.com
          SUBDOMAIN=dev
          EMAIL=admin@example.com
          CLOUDFLARE_API_TOKEN=cf_token_123
          CLOUDFLARE_ZONE_ID=abc123def456abc123def456abc123de
          ENABLE_AGENT_COPILOT=true
          ENABLE_AGENT_CLAUDE=false
          ENABLE_AGENT_GEMINI=false
          ENABLE_AGENT_CODEX=false
          ENABLE_AGENT_OPENCODE=true
          OPENAI_API_KEY=
          ANTHROPIC_API_KEY=
          GOOGLE_API_KEY=
          GITHUB_TOKEN=ghp_testtoken
          CODEX_OPENAI_AUTH_CODE=
          OPENCODE_PROVIDER=opencode-zen,github-copilot
          DEV_TOOLS=docker,node,python,kubectl

      - path: /etc/dev-server/bootstrap.sh
        permissions: "0700"
        content: |
          #!/usr/bin/env bash
          echo hello
""")

_RVS_CONFIG_SAMPLE = textwrap.dedent("""\
    # RVSconfig.yml — RemoteVibeServer configuration
    # Generated by the RemoteVibeServer Configurator.

    domain: "example.com"
    subdomain: "dev"
    email: "admin@example.com"
    cloudflare_api_token: "cf_token_123"
    cloudflare_zone_id: "abc123def456abc123def456abc123de"
    enable_agent_copilot: true
    enable_agent_claude: false
    enable_agent_gemini: false
    enable_agent_codex: false
    enable_agent_opencode: true
    openai_api_key: ""
    anthropic_api_key: ""
    google_api_key: ""
    github_token: "ghp_testtoken"
    codex_openai_auth_code: ""
    opencode_provider: "opencode-zen,github-copilot"
    dev_tools: "docker,node,python,kubectl"
""")


def _write_tmp(content: str, suffix: str = ".yaml") -> Path:
    """Write *content* to a temporary file and return its path."""
    fd, name = tempfile.mkstemp(suffix=suffix)
    try:
        os.write(fd, content.encode("utf-8"))
    finally:
        os.close(fd)
    return Path(name)


# ---------------------------------------------------------------------------
# parse_cloud_init
# ---------------------------------------------------------------------------

class TestParseCloudInit(unittest.TestCase):

    def setUp(self):
        self.path = _write_tmp(_CLOUD_INIT_SAMPLE)

    def tearDown(self):
        self.path.unlink(missing_ok=True)

    def test_domain(self):
        self.assertEqual(parse_cloud_init(self.path)["domain"], "example.com")

    def test_subdomain(self):
        self.assertEqual(parse_cloud_init(self.path)["subdomain"], "dev")

    def test_email(self):
        self.assertEqual(parse_cloud_init(self.path)["email"], "admin@example.com")

    def test_cloudflare_token(self):
        self.assertEqual(parse_cloud_init(self.path)["cloudflare_api_token"], "cf_token_123")

    def test_cloudflare_zone_id(self):
        self.assertEqual(parse_cloud_init(self.path)["cloudflare_zone_id"],
                         "abc123def456abc123def456abc123de")

    def test_agent_copilot_true(self):
        self.assertIs(parse_cloud_init(self.path)["enable_agent_copilot"], True)

    def test_agent_claude_false(self):
        self.assertIs(parse_cloud_init(self.path)["enable_agent_claude"], False)

    def test_agent_opencode_true(self):
        self.assertIs(parse_cloud_init(self.path)["enable_agent_opencode"], True)

    def test_github_token(self):
        self.assertEqual(parse_cloud_init(self.path)["github_token"], "ghp_testtoken")

    def test_opencode_provider(self):
        self.assertEqual(parse_cloud_init(self.path)["opencode_provider"],
                         "opencode-zen,github-copilot")

    def test_dev_tools(self):
        self.assertEqual(parse_cloud_init(self.path)["dev_tools"],
                         "docker,node,python,kubectl")

    def test_empty_key_preserved(self):
        result = parse_cloud_init(self.path)
        self.assertIn("openai_api_key", result)
        self.assertEqual(result["openai_api_key"], "")

    def test_missing_env_block_returns_empty(self):
        p = _write_tmp("#cloud-config\nwrite_files:\n  - path: /other\n    content: |\n      FOO=bar\n")
        try:
            self.assertEqual(parse_cloud_init(p), {})
        finally:
            p.unlink(missing_ok=True)

    def test_non_existent_file_raises(self):
        with self.assertRaises(Exception):
            parse_cloud_init("/nonexistent/path/cloud-init.yaml")


# ---------------------------------------------------------------------------
# parse_rvs_config
# ---------------------------------------------------------------------------

class TestParseRvsConfig(unittest.TestCase):

    def setUp(self):
        self.path = _write_tmp(_RVS_CONFIG_SAMPLE, suffix=".yml")

    def tearDown(self):
        self.path.unlink(missing_ok=True)

    def test_domain(self):
        self.assertEqual(parse_rvs_config(self.path)["domain"], "example.com")

    def test_subdomain(self):
        self.assertEqual(parse_rvs_config(self.path)["subdomain"], "dev")

    def test_email(self):
        self.assertEqual(parse_rvs_config(self.path)["email"], "admin@example.com")

    def test_cloudflare_token(self):
        self.assertEqual(parse_rvs_config(self.path)["cloudflare_api_token"], "cf_token_123")

    def test_bool_true(self):
        self.assertIs(parse_rvs_config(self.path)["enable_agent_copilot"], True)

    def test_bool_false(self):
        self.assertIs(parse_rvs_config(self.path)["enable_agent_claude"], False)

    def test_quoted_string(self):
        self.assertEqual(parse_rvs_config(self.path)["github_token"], "ghp_testtoken")

    def test_empty_quoted_string(self):
        result = parse_rvs_config(self.path)
        self.assertEqual(result["openai_api_key"], "")

    def test_multivalue_opencode_provider(self):
        self.assertEqual(parse_rvs_config(self.path)["opencode_provider"],
                         "opencode-zen,github-copilot")

    def test_dev_tools(self):
        self.assertEqual(parse_rvs_config(self.path)["dev_tools"],
                         "docker,node,python,kubectl")

    def test_escaped_double_quote(self):
        content = 'domain: "ex\\"ample.com"\n'
        p = _write_tmp(content, suffix=".yml")
        try:
            self.assertEqual(parse_rvs_config(p)["domain"], 'ex"ample.com')
        finally:
            p.unlink(missing_ok=True)

    def test_escaped_backslash(self):
        content = r'domain: "ex\\ample.com"' + "\n"
        p = _write_tmp(content, suffix=".yml")
        try:
            self.assertEqual(parse_rvs_config(p)["domain"], "ex\\ample.com")
        finally:
            p.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# load_config_file
# ---------------------------------------------------------------------------

class TestLoadConfigFile(unittest.TestCase):

    def test_load_cloud_init(self):
        p = _write_tmp(_CLOUD_INIT_SAMPLE)
        try:
            result = load_config_file(p)
            self.assertEqual(result["domain"], "example.com")
            self.assertIs(result["enable_agent_copilot"], True)
        finally:
            p.unlink(missing_ok=True)

    def test_load_rvs_config(self):
        p = Path(tempfile.mkdtemp()) / "RVSconfig.yml"
        p.write_text(_RVS_CONFIG_SAMPLE, encoding="utf-8")
        try:
            result = load_config_file(p)
            self.assertEqual(result["domain"], "example.com")
        finally:
            p.unlink(missing_ok=True)

    def test_empty_file_returns_empty_dict(self):
        p = _write_tmp("")
        try:
            self.assertEqual(load_config_file(p), {})
        finally:
            p.unlink(missing_ok=True)

    def test_garbage_returns_empty_dict(self):
        p = _write_tmp("this is not a config file\nrandom: stuff\n")
        try:
            self.assertEqual(load_config_file(p), {})
        finally:
            p.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# find_config_files
# ---------------------------------------------------------------------------

class TestFindConfigFiles(unittest.TestCase):

    def test_finds_cloud_init(self):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "cloud-init.yaml"
            p.write_text(_CLOUD_INIT_SAMPLE, encoding="utf-8")
            found = find_config_files(d)
            self.assertIn(p, found)

    def test_finds_rvs_config(self):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "RVSconfig.yml"
            p.write_text(_RVS_CONFIG_SAMPLE, encoding="utf-8")
            found = find_config_files(d)
            self.assertIn(p, found)

    def test_finds_both(self):
        with tempfile.TemporaryDirectory() as d:
            ci = Path(d) / "cloud-init.yaml"
            ci.write_text(_CLOUD_INIT_SAMPLE, encoding="utf-8")
            rv = Path(d) / "RVSconfig.yml"
            rv.write_text(_RVS_CONFIG_SAMPLE, encoding="utf-8")
            found = find_config_files(d)
            self.assertIn(ci, found)
            self.assertIn(rv, found)

    def test_empty_dir_returns_empty(self):
        with tempfile.TemporaryDirectory() as d:
            self.assertEqual(find_config_files(d), [])

    def test_glob_cloud_init_variants(self):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "cloud-init.old.yaml"
            p.write_text(_CLOUD_INIT_SAMPLE, encoding="utf-8")
            found = find_config_files(d)
            self.assertIn(p, found)

    def test_sorted_newest_first(self):
        with tempfile.TemporaryDirectory() as d:
            old = Path(d) / "cloud-init.yaml"
            old.write_text(_CLOUD_INIT_SAMPLE, encoding="utf-8")
            import time
            time.sleep(0.01)
            new = Path(d) / "RVSconfig.yml"
            new.write_text(_RVS_CONFIG_SAMPLE, encoding="utf-8")
            found = find_config_files(d)
            self.assertEqual(found[0], new)


if __name__ == "__main__":
    unittest.main()
