"""Generate cloud-init YAML and RVSconfig.yml from user configuration."""

from __future__ import annotations

import textwrap
from typing import Any

# We build the cloud-init output as a plain string (not via a YAML library)
# to preserve comments and literal-block scalars.  The embedded template is
# functionally equivalent to ``cloud-init.example.yaml`` but the header
# comments differ (e.g. placeholder guidance is replaced by a "generated"
# notice).

_CLOUD_INIT_TEMPLATE = textwrap.dedent("""\
    #cloud-config
    # =============================================================================
    # RemoteVibeServer — Cloud-Init Configuration
    # =============================================================================
    # Generated by the RemoteVibeServer Configurator.
    #
    # IMPORTANT: This file contains secrets.  NEVER commit it to version control.
    # =============================================================================

    # ---------------------------------------------------------------------------
    # 1. Package bootstrap
    # ---------------------------------------------------------------------------
    package_update: true
    package_upgrade: true

    packages:
      - curl
      - wget
      - git
      - jq
      - unzip
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - ufw
      - fail2ban
      - certbot

    # ---------------------------------------------------------------------------
    # 2. Secure environment file
    # ---------------------------------------------------------------------------
    write_files:
      - path: /etc/dev-server/env
        permissions: "0600"
        owner: root:root
        content: |
          # ── Domain & DNS ──────────────────────────────────────────────────
          DOMAIN={domain}
          SUBDOMAIN={subdomain}
          EMAIL={email}

          # ── Cloudflare ────────────────────────────────────────────────────
          CLOUDFLARE_API_TOKEN={cloudflare_api_token}
          CLOUDFLARE_ZONE_ID={cloudflare_zone_id}

          # ── Coder ─────────────────────────────────────────────────────────
          CODER_URL=https://{subdomain}.{domain}
          CODER_ACCESS_URL=https://{subdomain}.{domain}
          # Admin login password (Coder requires ≥ 8 chars, no spaces).
          # Login email is the address entered above.  Username: admin
          CODER_ADMIN_PASSWORD={coder_admin_password}

          # ── AI Agent Flags (true / false) ─────────────────────────────────
          ENABLE_AGENT_COPILOT={enable_agent_copilot}
          ENABLE_AGENT_CLAUDE={enable_agent_claude}
          ENABLE_AGENT_GEMINI={enable_agent_gemini}
          ENABLE_AGENT_CODEX={enable_agent_codex}
          ENABLE_AGENT_OPENCODE={enable_agent_opencode}

          # ── AI Agent API Keys (leave empty to skip) ───────────────────────
          OPENAI_API_KEY={openai_api_key}
          ANTHROPIC_API_KEY={anthropic_api_key}
          GOOGLE_API_KEY={google_api_key}
          GITHUB_TOKEN={github_token}

          # ── Codex CLI OpenAI OAuth (leave empty if using API key) ──────
          CODEX_OPENAI_AUTH_CODE={codex_openai_auth_code}

          # ── OpenCode Provider Selection ────────────────────────────────────
          OPENCODE_PROVIDER={opencode_provider}

      - path: /etc/dev-server/bootstrap.sh
        permissions: "0700"
        owner: root:root
        content: |
          #!/usr/bin/env bash
          # Thin bootstrap — downloads the full provisioning suite and runs it.
          set -euo pipefail

          # Suppress interactive prompts from apt/dpkg and needrestart during provisioning.
          export DEBIAN_FRONTEND=noninteractive
          export NEEDRESTART_MODE=a

          # cloud-init runcmd runs without a login shell — HOME is not set.
          export HOME="${{HOME:-/root}}"

          REPO_URL="https://raw.githubusercontent.com/PhilippWu/RemoteVibeServer/main/dev-server-provision"
          PROVISION_DIR="/opt/dev-server-provision"

          mkdir -p "$PROVISION_DIR/infra" "$PROVISION_DIR/coder"

          echo "[bootstrap] Downloading provisioning scripts …"
          for f in setup.sh infra/dns.sh infra/proxy.sh infra/agents.sh coder/Dockerfile coder/devcontainer.json coder/main.tf; do
            curl -fsSL "$REPO_URL/$f" -o "$PROVISION_DIR/$f"
          done
          chmod +x "$PROVISION_DIR/setup.sh" "$PROVISION_DIR/infra/"*.sh

          echo "[bootstrap] Starting setup …"
          exec "$PROVISION_DIR/setup.sh"

    # ---------------------------------------------------------------------------
    # 3. Run bootstrap on first boot
    # ---------------------------------------------------------------------------
    runcmd:
      # Install Docker (official method)
      - |
        export DEBIAN_FRONTEND=noninteractive
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg \\
          | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo \\
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \\
          https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \\
          > /etc/apt/sources.list.d/docker.list
        apt-get update -y
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      # Enable and start Docker
      - systemctl enable --now docker

      # Configure firewall
      - ufw default deny incoming
      - ufw default allow outgoing
      - ufw allow 22/tcp
      - ufw allow 80/tcp
      - ufw allow 443/tcp
      - ufw allow 3000:9999/tcp   # development services (APIs, databases, frontends)
      - ufw --force enable

      # Enable fail2ban
      - systemctl enable --now fail2ban

      # Run the bootstrap script
      - /etc/dev-server/bootstrap.sh 2>&1 | tee /var/log/dev-server-provision.log

    final_message: |
      ========================================
      RemoteVibeServer provisioning complete.
      Log: /var/log/dev-server-provision.log
      ========================================
""")


def generate_cloud_init(config: dict[str, Any]) -> str:
    """Return a fully rendered cloud-init YAML string.

    *config* must contain the keys used in ``_CLOUD_INIT_TEMPLATE``.
    Boolean agent flags are normalised to ``"true"`` / ``"false"``.
    """
    # Normalise booleans → lowercase strings
    normalised: dict[str, str] = {}
    for key, value in config.items():
        if isinstance(value, bool):
            normalised[key] = "true" if value else "false"
        else:
            normalised[key] = str(value) if value is not None else ""
    return _CLOUD_INIT_TEMPLATE.format(**normalised)


def default_config() -> dict[str, Any]:
    """Return a config dict pre-filled with safe defaults."""
    return {
        "domain": "",
        "subdomain": "dev",
        "email": "",
        "cloudflare_api_token": "",
        "cloudflare_zone_id": "",
        "coder_admin_password": "",
        "enable_agent_copilot": False,
        "enable_agent_claude": False,
        "enable_agent_gemini": False,
        "enable_agent_codex": False,
        "enable_agent_opencode": False,
        "openai_api_key": "",
        "anthropic_api_key": "",
        "google_api_key": "",
        "github_token": "",
        "codex_openai_auth_code": "",
        "opencode_provider": "",
    }


# ---------------------------------------------------------------------------
# RVSconfig.yml generation
# ---------------------------------------------------------------------------

# The key order used when writing RVSconfig.yml — keeps the output tidy and
# predictable.
_RVS_KEY_ORDER: list[str] = [
    "domain",
    "subdomain",
    "email",
    "cloudflare_api_token",
    "cloudflare_zone_id",
    "coder_admin_password",
    "enable_agent_copilot",
    "enable_agent_claude",
    "enable_agent_gemini",
    "enable_agent_codex",
    "enable_agent_opencode",
    "openai_api_key",
    "anthropic_api_key",
    "google_api_key",
    "github_token",
    "codex_openai_auth_code",
    "opencode_provider",
]


def _yaml_escape(value: str) -> str:
    r"""Escape a string for safe inclusion in a double-quoted YAML scalar.

    Handles backslashes, double quotes, and newlines so the generated
    ``RVSconfig.yml`` is always valid YAML.
    """
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def generate_rvs_config(config: dict[str, Any]) -> str:
    """Return a simple YAML string (``RVSconfig.yml``) from *config*.

    The file is designed to be copy-pasted into ``install.sh`` on a bare
    Ubuntu server.  Boolean flags are written as ``true`` / ``false``.
    Empty values are represented as empty strings (``key: ""``).
    """
    lines: list[str] = [
        "# RVSconfig.yml — RemoteVibeServer configuration",
        "# Generated by the RemoteVibeServer Configurator.",
        "# Paste this into the install.sh prompt on your server.",
        "",
    ]
    for key in _RVS_KEY_ORDER:
        value = config.get(key)
        if isinstance(value, bool):
            lines.append(f"{key}: {str(value).lower()}")
        elif value:
            lines.append(f'{key}: "{_yaml_escape(str(value))}"')
        else:
            lines.append(f"{key}: \"\"")
    lines.append("")  # trailing newline
    return "\n".join(lines)
